### PR TITLE
Redesigned power supply

### PR DESCRIPTION
**Pull request by WaldoBorek**
1. Redesigned power supply. Very small linear regulator with included reverse polarity. Only one external capacitor needed.
2. Added button
3. Added prog connector

### CODE REVIEW

**Comment by mv4wd** [comment]
This is a nice change to make the circuit smaller. 
Few things to notice: max operating voltage is 20V, vs 30V of lp2950cz. If running form bec, it should be no problem. I'm afraid programming with full circuit mounted (through J2 connector) will overload the PSOC outputs beyond specs. The antenna is in parallel with the programming serial lines. It should be disconnected for programming.

**Comment by WaldoBorek** [comment]
Programming through J2 connector is working OK (with full circuit mounted)
Tests were done with:
1. MPLAB ICD3 programmer - works OK
2. Decoder RCHourglas (PSOC) - works OK

**Comment by WaldoBorek** [comment]
There is one more change/option - 20MHz crystal. Of course, software needs to be changed.   
With small crystal it is possible to reduce size of transponder to 15x15mm
Today I build transponder with integrated antenna and small crystal. Works fine.

screenshot 107

**Comment by mv4wd** [comment]
Added contrib subfolder under transponder schematic

**Pull request closed without merging**
